apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-deploy
  name: java-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-deploy
    spec:
      containers:
      - image: jayanthroyg/javaimage:latest
        name: javaimage
        ports:
        - containerPort: 8080
        resources: {}
status: {}
