apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-deploy
  name: java-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-deploy
  type: NodePort
status:
  loadBalancer: {}
